global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082', 'host.docker.internal:8083', 'host.docker.internal:8084']  # Update with the correct ports for your microservices
